f = figure('color','white','Position',...
[360, 500, 800,600]);

% Put a name on it and move it to the center of the screen set(f,'Name','GUI with editable text')
movegui(f,'center')

% Create two objects: a box where the user can type and
% edit a string and also a text title for the edit box 
hsttext = uicontrol('Style','text',...
'BackgroundColor','white',...
    'Position',[100,425,400,55],...
    'String','Please recall as many as words possible, separated by a space');

huitext = uicontrol('Style','edit',...
    'Position',[100,400,400,40]);

huibutton = uicontrol('Style','pushbutton',...
    'Position',[100,100,400,40],...
    'callback', 'get(huitext,''String''); clf')



