

fig = figure('units','normalized',...
    'outerposition',[0 0 1 1]);

ax = axes(fig,'xcolor',get(gcf,'color'),...
    'position', [0 0 1 1],...
    'xtick',[],...
    'ycolor',get(gcf,'color'),...
    'ytick',[]);

hsttext = uicontrol('Style','text',...
    'BackgroundColor','white',... 
    'Position',[.3 .3 .1 .2],... 
    'String','Enter your string here');

huitext = uicontrol('Style','edit',... 
    'units', 'normalized',...
    'Position',[.5 .5 .3 .3],...
    'Callback',@callbackfn);